# Generated by Django 2.2.3 on 2019-08-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20190815_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo_url',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
