# Generated by Django 2.2.3 on 2019-08-17 12:35

import crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20190817_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.FileField(null=True, upload_to=crm.models.get_file_path),
        ),
    ]
